//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibraryModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Evaluacion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Evaluacion()
        {
            this.Detalle_Materia = new HashSet<Detalle_Materia>();
        }
    
        public int idEvaluacion { get; set; }
        public int idMateria { get; set; }
        public int idTrimestre { get; set; }
        public int idUsuario { get; set; }
        public int idAlumno { get; set; }
        public decimal nota1 { get; set; }
        public decimal nota2 { get; set; }
        public decimal nota3 { get; set; }
        public decimal promedio { get; set; }
        public Nullable<int> valorNota { get; set; }
        public string Estado { get; set; }
    
        public virtual Alumno Alumno { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Detalle_Materia> Detalle_Materia { get; set; }
        public virtual Trimestre Trimestre { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
