//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibraryModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grado
    {
        public int idGrado { get; set; }
        public int idSeccion { get; set; }
        public System.DateTime anioCurso { get; set; }
        public string aula { get; set; }
    
        public virtual Seccion Seccion { get; set; }
    }
}
